
'use client';

import { Button } from '@/components/ui/button';
import Link from 'next/link';
import { LoksewaLogo } from '@/components/icons/loksewa-logo';
import { CheckCircle, Zap, FlaskConical, BarChart, Wand, FileText } from 'lucide-react';
import Image from 'next/image';
import { useAuth } from '@/contexts/auth-context';
import { useRouter } from 'next/navigation';
import { useEffect } from 'react';

const features = [
  {
    icon: Zap,
    title: 'Daily Quizzes',
    description: 'Stay sharp with daily practice quizzes generated by AI, offering instant feedback.',
  },
  {
    icon: FileText,
    title: 'Full Mock Tests',
    description: 'Simulate the real exam with timed mock tests covering the entire syllabus.',
  },
  {
    icon: FlaskConical,
    title: 'Custom Test Generator',
    description: 'Create personalized tests by topic and difficulty to focus on your weak areas.',
  },
  {
    icon: Wand,
    title: 'AI Study Planner',
    description: 'Get a customized, week-by-week study plan tailored to your exam date and goals.',
  },
  {
    icon: BarChart,
    title: 'Performance Analytics',
    description: 'Visualize your progress over time with clear charts and performance tracking.',
  },
  {
      icon: CheckCircle,
      title: 'Vast Question Bank',
      description: 'Access thousands of questions across all major IT and general knowledge topics.'
  }
];

const subjects = [
    'Computer Fundamentals',
    'Object Oriented Programming',
    'Data Structure & Algorithms',
    'Database Management System',
    'Computer Networks & Security',
    'Software Engineering',
    'MIS and Web Technologies',
    'Recent IT Trends',
];

export default function LandingPage() {
    const { user, loading } = useAuth();
    const router = useRouter();

    useEffect(() => {
        if (!loading && user) {
            router.push('/dashboard');
        }
    }, [user, loading, router]);
    
  return (
    <div className="flex min-h-screen flex-col bg-background">
      <header className="sticky top-0 z-40 w-full border-b bg-background/95 backdrop-blur-sm">
        <div className="container mx-auto flex h-14 items-center justify-between px-4 md:px-6">
          <Link href="/" className="flex items-center gap-2">
            <LoksewaLogo className="h-8 w-8 text-primary" />
            <span className="font-bold">Loksewa Prep</span>
          </Link>
          <nav className="flex items-center gap-4">
             <Button asChild>
                <Link href="/login">Get Started</Link>
             </Button>
          </nav>
        </div>
      </header>

      <main className="flex-1">
        {/* Hero Section */}
        <section className="relative py-20 md:py-28">
            <div 
                aria-hidden="true" 
                className="absolute inset-0 grid grid-cols-2 -space-x-52 opacity-40 dark:opacity-20"
            >
                <div className="blur-[106px] h-56 bg-gradient-to-br from-primary to-purple-400 dark:from-blue-700"></div>
                <div className="blur-[106px] h-32 bg-gradient-to-r from-cyan-400 to-sky-300 dark:to-indigo-600"></div>
            </div>
            <div className="container mx-auto px-4 md:px-6 grid md:grid-cols-2 gap-12 items-center">
                <div className="text-center md:text-left">
                    <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">
                        Your Ultimate AI Partner for Loksewa Exams
                    </h1>
                    <p className="mt-6 max-w-[600px] text-muted-foreground md:text-xl">
                        Ace your Loksewa IT Officer exam with AI-powered mock tests, personalized study plans, and detailed performance analytics.
                    </p>
                    <div className="mt-8 flex justify-center md:justify-start">
                        <Button asChild size="lg">
                            <Link href="/login">Start Preparing Now</Link>
                        </Button>
                    </div>
                </div>
                 <div className="relative h-64 md:h-96">
                    <Image 
                        src="public/dbeb6909-b451-42f7-ab29-c91b62e6134d.png"
                        data-ai-hint="student studying computer"
                        alt="Student studying for an exam" 
                        fill
                        className="object-contain rounded-lg"
                    />
                </div>
            </div>
        </section>

        {/* Features Section */}
        <section id="features" className="py-20 md:py-28 bg-muted/50">
            <div className="container mx-auto px-4 md:px-6">
                <div className="mx-auto max-w-2xl text-center">
                    <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Everything You Need to Succeed</h2>
                    <p className="mt-4 text-muted-foreground">
                        Our platform is packed with features designed to make your exam preparation effective and efficient.
                    </p>
                </div>
                <div className="mt-12 grid gap-8 md:grid-cols-2 lg:grid-cols-3">
                    {features.map((feature) => (
                    <div key={feature.title} className="flex flex-col items-start gap-4 rounded-lg border bg-card p-6 shadow-sm transition-all hover:shadow-md hover:-translate-y-1">
                        <div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary/10">
                            <feature.icon className="h-6 w-6 text-primary" />
                        </div>
                        <h3 className="text-xl font-bold">{feature.title}</h3>
                        <p className="text-muted-foreground">{feature.description}</p>
                    </div>
                    ))}
                </div>
            </div>
        </section>

        {/* Subjects Section */}
        <section id="subjects" className="py-20 md:py-28">
            <div className="container mx-auto px-4 md:px-6">
                 <div className="mx-auto max-w-2xl text-center">
                    <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Subjects We Cover</h2>
                    <p className="mt-4 text-muted-foreground">
                        Our question bank covers all the essential topics from the official IT Officer syllabus.
                    </p>
                </div>
                 <div className="mt-12 grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
                    {subjects.map((subject) => (
                        <div key={subject} className="flex items-center gap-3 rounded-lg border bg-card p-4 shadow-sm">
                            <CheckCircle className="h-5 w-5 text-green-500" />
                            <span className="font-medium">{subject}</span>
                        </div>
                    ))}
                </div>
            </div>
        </section>
        
        {/* Final CTA */}
        <section className="py-20 md:py-28">
             <div className="container mx-auto px-4 md:px-6 text-center">
                 <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Ready to Start Your Journey?</h2>
                <p className="mx-auto mt-4 max-w-[600px] text-muted-foreground md:text-lg">
                    Join thousands of successful candidates. Sign up now and get immediate access to all our preparation tools.
                </p>
                <div className="mt-8 flex justify-center">
                    <Button asChild size="lg">
                        <Link href="/login">Get Started for Free</Link>
                    </Button>
                </div>
            </div>
        </section>

      </main>

      <footer className="border-t py-6 md:py-8">
        <div className="container mx-auto flex flex-col items-center justify-between gap-4 px-4 md:flex-row md:px-6">
            <div className="flex items-center gap-2">
                 <LoksewaLogo className="h-6 w-6 text-primary" />
                 <span className="font-semibold">Loksewa Prep</span>
            </div>
             <div className="flex justify-center items-center gap-x-4 gap-y-2 flex-wrap text-sm text-muted-foreground">
                <span>Developed by Raymond Maharjan</span>
                <span className="hidden sm:inline">|</span>
                <span>&copy; {new Date().getFullYear()} Loksewa Prep</span>
                <span className="hidden sm:inline">|</span>
                <Link href="/terms-of-service" className="hover:text-primary hover:underline">
                    Terms of Service
                </Link>
                <span className="hidden sm:inline">|</span>
                <Link href="/privacy-policy" className="hover:text-primary hover:underline">
                    Privacy Policy
                </Link>
            </div>
        </div>
      </footer>
    </div>
  );
}
