
'use client';

import { LandingFooter } from '@/components/layout/landing-footer';
import { LandingHeader } from '@/components/layout/landing-header';
import { Button, buttonVariants } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { CheckCircle, BarChart, FlaskConical, Zap, Target } from 'lucide-react';
import Image from 'next/image';
import Link from 'next/link';


const features = [
    {
        icon: <Zap className="h-8 w-8 text-primary" />,
        title: "AI-Powered Quizzes",
        description: "Get daily quizzes and mock tests generated by AI to keep your preparation sharp and relevant.",
    },
    {
        icon: <FlaskConical className="h-8 w-8 text-primary" />,
        title: "Custom Test Generator",
        description: "Create your own tests by selecting topics and difficulty levels to focus on your weak areas.",
    },
    {
        icon: <BarChart className="h-8 w-8 text-primary" />,
        title: "Performance Analytics",
        description: "Visualize your progress with clear charts and track your performance over time to identify strengths.",
    },
    {
        icon: <Target className="h-8 w-8 text-primary" />,
        title: "Personalized Study Plans",
        description: "Let our AI create a customized study schedule based on your goals and available time.",
    },
]

export default function LandingPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <LandingHeader />
      <main className="flex-1">
        {/* Hero Section */}
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48 bg-gradient-to-br from-background to-secondary/40">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    The Ultimate AI-Powered Loksewa Prep Tool
                  </h1>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl">
                    Ace your Loksewa exams with personalized quizzes, mock tests, and performance analytics, all driven by cutting-edge AI.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="/login"
                    className={buttonVariants({size: 'lg'})}
                  >
                    Get Started
                  </Link>
                  <Link
                    href="#features"
                    className={buttonVariants({variant: 'outline', size: 'lg'})}
                  >
                    Learn More
                  </Link>
                </div>
              </div>
              <Image
                src="https://placehold.co/600x400.png"
                width="600"
                height="400"
                alt="Hero"
                data-ai-hint="students studying technology"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last"
              />
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section id="features" className="w-full py-12 md:py-24 lg:py-32 bg-background">
            <div className="container px-4 md:px-6">
                 <div className="flex flex-col items-center justify-center space-y-4 text-center mb-12">
                    <div className="space-y-2">
                        <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Key Features</div>
                        <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Why Choose Loksewa Prep?</h2>
                        <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                            Our platform is built to provide you with the tools you need to succeed.
                        </p>
                    </div>
                </div>
                <div className="mx-auto grid max-w-5xl items-start gap-8 sm:grid-cols-2 md:gap-12 lg:max-w-none lg:grid-cols-4">
                    {features.map((feature, index) => (
                         <div key={index} className="grid gap-4 text-center">
                           <div className="mx-auto bg-primary/10 p-4 rounded-full">
                                {feature.icon}
                           </div>
                           <div className="grid gap-1">
                                <h3 className="text-lg font-bold">{feature.title}</h3>
                                <p className="text-sm text-muted-foreground">{feature.description}</p>
                           </div>
                        </div>
                    ))}
                </div>
            </div>
        </section>

         {/* How It Works Section */}
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted/40">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">How It Works</h2>
              <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Start your journey to exam success in three simple steps.
              </p>
            </div>
            <div className="mx-auto w-full max-w-5xl grid grid-cols-1 sm:grid-cols-3 gap-8 pt-8">
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">1. Sign Up</h3>
                <p className="text-sm text-muted-foreground">Create your account with one click using Google.</p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">2. Practice</h3>
                <p className="text-sm text-muted-foreground">Take AI-generated quizzes and mock tests tailored to you.</p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">3. Analyze & Improve</h3>
                <p className="text-sm text-muted-foreground">Track your performance and focus on your weak areas.</p>
              </div>
            </div>
          </div>
        </section>
        
        {/* CTA Section */}
        <section className="w-full py-12 md:py-24 lg:py-32">
             <div className="container px-4 md:px-6">
                <div className="flex flex-col items-center space-y-4 text-center">
                    <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Ready to Start Your Prep?</h2>
                    <p className="max-w-[600px] text-muted-foreground md:text-xl">
                        Join today and take the first step towards your dream government job.
                    </p>
                    <Link href="/login" className={buttonVariants({ size: 'lg' })}>
                        Sign Up for Free
                    </Link>
                </div>
            </div>
        </section>

      </main>
      <LandingFooter />
    </div>
  );
}
